# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: c271d2839bfc8084e87cdbc4ef2982f431ad078e

authentication:
    type: CAS # possible values are CAS or FORM
    
async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost # mail server
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: securityRAT@localhost # from email address


swagger:
    title: SecurityRAT
    description: SecurityRAT applications and beyond!
    version: 1.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
